config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  belongs_to :user
  has_many :pictures, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :tag_line, presence: true
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, uniqueness: { case_sensitive: false },
            presence: true, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, uniqueness: { case_sensitive: false },
            presence: true, length: {maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }

  has_many :albums, dependent: :destroy

  has_secure_password
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new()
  end

  def create
    @album = Album.new(name: params[:album][:name])
    @album.user_id = current_user.id
    if @album.save
      flash[:notice] = "Albums Saved succesfully"
      redirect_to @album
    else
      render 'new'
    end
  end

  def show
    @album = Album.find(params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user

  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def home
    @pictures = Picture.last(25)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture_and_album, only: [:edit, :update, :destroy]
  before_action :require_user, except: [:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @album = Album.find(params[:album])
    @picture = Picture.new(album_id: @album.id)
  end

  def create
    @picture = Picture.new(picture_params)
    @album = Album.find(@picture.album_id)
    if @album.pictures.count < 25 && @picture.save
      flash[:notice] = "Picture Saved succesfully"
      redirect_to @album
    else
      flash[:notice] = "More than 25 Pictures cannot be created, Please create new album" if @album.pictures.count >= 25
      render 'new'
    end
  end

  def edit

  end

  def destroy
    @picture.destroy
    redirect_to @album
  end

  def update
    if @picture.update(tag_line: params[:picture][:tag_line])
      flash[:notice] = "Picture Updated Succesfully"
      redirect_to @album
    else
      render 'edit'
    end
    end

  private

  def set_picture_and_album
    @picture = Picture.find(params[:id])
    @album = Album.find(@picture.album_id)
  end

  def picture_params
    params.require(:picture).permit(:tag_line, :album_id,:avatar)
  end

  def require_same_user
    if ( current_user != @album.user)
      flash[:alert] = "You can edit your's album only"
      redirect_to @album
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfuly"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your credetianls you entered"
      render 'new'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]


  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Images blog #{@user.username} "
      redirect_to login_path
    else
      render 'new'
    end
  end

  def show
    @albums = @user.albums
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<table>
  <thead>
  <th>ALbum Name</th>
  <% if logged_in? %>
  <th colspan="3"> Action </th>
  <% end %>
  </thead>

  <tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to  album.name, album_path(album)%></td>
      <% if logged_in? && (current_user.id == album.user_id) %>
        <td> <%= 'Edit '%></td>
        <td><%= 'Delete' %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>


<body>
<br/>
<p><%= link_to 'Create New Album', new_album_path()%></p>

</body>

app/views/albums/_form.html.erb
<% if @album.errors.any? %>
  <h2>Below are the errors preventing albums to get saved</h2>
  <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @album, local: true ) do |f| %>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name%>
  </p>

  <p>
    <%= f.submit %><br/>
  </p>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit album </h1>
<%= render 'form' %>
<%= link_to 'Return to Albums Listing', current_user %>

app/views/albums/index.html.erb

<%= render 'album' %>

app/views/albums/new.html.erb
<h1>New Album </h1>
<%= render 'form' %>
<%= link_to 'Return to Albums Listing', current_user %>

app/views/albums/show.html.erb
<h1> Showing album details </h1>
<p><strong> Name: </strong><%= @album.name %></p>

<%= link_to 'Return to Albums Listing',current_user %>

app/views/homepages/home.html.erb
<h1>Welcome to Images Blog</h1>

<ul class="list-group">
  <li class="list-group-item"><%= link_to 'Albums', albums_path %></li>
  <% if logged_in?%>
    <li class="list-group-item"><%= link_to 'logout', logout_path, method: :delete %></li>
<% else %>
    <li class="list-group-item"><%= link_to 'Login', login_path() %></li>
    <li class="list-group-item"><%= link_to 'Signup', signup_path() %></li>
  <% end %>

</ul>
<%= render 'pictures/picture' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImagesBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <h2>Below are the errors preventing albums to get saved</h2>
  <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @picture, local: true ) do |f| %>
  <%= f.hidden_field :album_id %>
  <p>
    <%= f.label :tag_line %><br/>
    <%= f.text_field :tag_line%>
  </p>

  <p>
    <%= f.label :avatar %> <br/>
    <%= f.file_field  :avatar %>
  </p>

  <p>
    <%= f.submit %><br/>
  </p>
<% end %>

app/views/pictures/_picture.html.erb
 <tbody>
  <% @pictures.each do |picture| %>
    <tr>
    <tr><h4><%= picture.tag_line%></h4></tr>
   <% if request[:action] == "home" %>
   <tr>Uploaded by: <%= picture.album.user.username%></tr>
     <% end %>
    <td><%= image_tag picture.avatar.url%></td>
    <br>
      <% if logged_in? && @album.present? && (current_user.id == @album.user_id) %>
        <tr> <%= link_to 'Edit ', edit_picture_path(picture)%></tr>
        <tr><%= link_to ' Delete ', picture_path(picture), method: :delete, data: {confirm: "Are you sure want to delete this?"} %></tr>
      <% end %>
    <br>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/pictures/edit.html.erb
<h1>Edit Picture </h1>
<% if @picture.errors.any? %>
  <h2>Below are the errors preventing albums to get saved</h2>
  <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @picture, local: true ) do |f| %>
  <%= f.hidden_field :album_id %>
  <p>
    <%= f.label :tag_line %><br/>
    <%= f.text_field :tag_line%>
  </p>

  <p>
    <%= f.submit %><br/>
  </p>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture </h1>
<%= render 'form' %>
<%= link_to 'Return to Albums Listing', current_user %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h2>Below are the errors preventing users to get signup</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @user, local: true ) do |f| %>

  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username%>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email%>
  </p>

  <p>
    <%= f.label :password %><br/>
    <%= f.text_field :password%>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Signup" : "Update account") %><br/>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= render 'form' %>
<%= link_to 'Delete Profile', user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete you'r profile"}%>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s details </h1>
<p><strong> Name: </strong><%= @user.username %></p>
<p><strong>Email:</strong><%= @user.email %> </p>
<%= render 'albums/album' %>